### ISSUE TITLE
LRBfact

### ISSUE THREAD

**Issue by nevrome** [benmarwick/binford#1]
Thanks for compiling and presenting this great dataset as an R package. That makes it very easily accessible.  

For curiosity's sake: Why didn't you add the LRBfact table?

**Comment by benmarwick** [comment]
Thanks for your kind note. The reason I excluded that table is because [Amber Johnson says](http://ajohnson.sites.truman.edu/data-and-program/) that "LRBfact.csv is the same as LRB.csv except code values are represented by their label, rather than the code". So to keep this pkg small and simple, I decided not to include this duplicate dataset. What do you think?

**Comment by nevrome** [comment]
Hm... It's convenient to have the version with written labels available and LRBfact.rdata has just little over 300 KB. I suggest to add it. If you agree but don't want to do it yourself, I could prepare a PR.

In LRB there are already some columns that do exactly this (subsp -> subsp.1). They could be removed. But I don't know how deep you want to dive into the work of Amber Johnson.

**Comment by benmarwick** [comment]
Sure, I'd be happy to consider a pull request to add that table. I don't have any current plans to modify the data, I'd like to keep it as close as possible to Amber Johnson's files.
